### ISSUE TITLE
CORS error in Arnold prod

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/arnold#15]
https://cigrid.scilifelab.se/lab-preps/steps
![Screen Shot 2022-03-23 at 10 57 12](https://user-images.githubusercontent.com/6919697/159672862-65ee6f1b-fc19-4bff-becb-df56da2f4bdd.png)

**Comment by elevu** [comment]
fixed by Maria

**Comment by Mropat** [comment]
Was fixed by deploying a newer version of API in prod :+1:
