### ISSUE TITLE
Group 'string' showing up in some queries

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/arnold#22]
For example:
https://arnold-stage.scilifelab.se/api/v1/trends/sample_turnaround_times?field=prepped_to_sequenced&year=2022&group=customer
<img width="648" alt="Screen Shot 2022-04-12 at 15 02 29" src="https://user-images.githubusercontent.com/6919697/162968461-957d7cba-8f16-4d3f-b1c8-5e80a1a4964d.png">

**Comment by Mropat** [comment]
Curated and deleted the one outlier sample with those values, manually
