### ISSUE TITLE
Develop endpoint for Graph 1: Number of samples received (and delivered), broken down per month

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/arnold#34]
https://www.figma.com/file/Gz9eZYmbOfGa0UEezoJP6M/Graph-1%3A-Number-of-samples-received-(and-delivered)%2C-broken-down-per-month?node-id=0%3A1

**Comment by elevu** [comment]
The data object in the frontend library is a flat array that looks like this:
```
{
      label: '2021/01.',
      type: 'WGS',
      value: 200,
}
```
so the endpoints can return the data in any points. Preferred as arrays, like 
```
[
    { date: "2020/01", datapoints: [{ tag: "WGS", value: 80 },{ tag: "WSA", value: 80 }] },
    { date: "2020/02", datapoints: [{ tag: "WGS", value: 60 }, { tag: "WSA", value: 180 }] }
  ]
```

**Comment by Mropat** [comment]
Done
